#ADMINISTRATOR
DROP TABLE ADMIN;
CREATE TABLE ADMIN(
 AID VARCHAR(20) PRIMARY KEY,
 ANAME VARCHAR(20),
 APW VARCHAR(30) NOT NULL,
 ADATE timestamp DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO ADMIN VALUES('admin','Administrator','pw',sysdate);
SELECT * FROM ADMIN WHERE AID='admin';
SELECT * FROM ADMIN;
COMMIT;

#MEMBER
SELECT*FROM MEMBERS;
DROP TABLE MEMBERS;
CREATE TABLE MLEVEL(
  MLEVEL int(1) PRIMARY KEY,
  MLNAME VARCHAR(20) NOT NULL,
  MLLOWP int(5) NOT NULL,
  MLHIGHP int(5)
);
SELECT*FROM MLEVEL;
CREATE TABLE MEMBERS(
  MID VARCHAR(50) PRIMARY KEY,
  MNAME VARCHAR(30) UNIQUE,
  MPW VARCHAR(20) NOT NULL,
  MDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  MPHOTO VARCHAR(30) DEFAULT 'noimg.jpg',
  ABOUTME varchar(1000),
  MLEVEL int(1) DEFAULT 1 REFERENCES MLEVEL(MLEVEL),
  MPOINT int(5) DEFAULT 0,
  MDROP int(1) DEFAULT 0,
  MELIMI int(1) DEFAULT 0
);
DROP TABLE MEMBERS;
SELECT*FROM MEMBERS;
INSERT INTO MLEVEL VALUES(1,'NEWBIE',0,99);
INSERT INTO MLEVEL VALUES(2,'STUDENT',100,4999);
INSERT INTO MLEVEL VALUES(3,'ADVANCED',5000,9999);
INSERT INTO MLEVEL VALUES(4,'EXPERT',10000,99999);
UPDATE MLEVEL SET MLNAME='NEWBIE' WHERE MLEVEL=1;
ROLLBACK;
COMMIT;

INSERT INTO MEMBERS VALUES('haenemm@naver.com', 'Min Kyung', 'pw', DEFAULT, DEFAULT,NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO MEMBERS VALUES('choryon2@naver.com', 'blueberry', 'pw', sysdate, DEFAULT,NULL,2, 3500, DEFAULT, DEFAULT);

INSERT INTO MEMBERS (MID,MNAME,MPW,MPHOTO,ABOUTME) VALUES('haenemm@naver.com','Min Kyung', 'pw',default,null);
SELECT M.*, MLNAME, MLHIGHP FROM MEMBERS M, MLEVEL L WHERE M.MLEVEL=L.MLEVEL AND MID='haenemm@naver.com';
SELECT M.*, MLNAME, MLHIGHP FROM MEMBERS M, MLEVEL L WHERE M.MLEVEL=L.MLEVEL AND MID='choryon2@naver.com';

SELECT MID, MPOINT,L.MLEVEL MLNAME FROM MEMBERS M, MLEVEL L WHERE MPOINT BETWEEN MLLOWP AND MLHIGHP;
ROLLBACK;
COMMIT;

DROP TABLE MYQBOOK;
DROP TABLE SOURCE_INFO;
DROP TABLE VOCANOTE;
CREATE TABLE MYQBOOK(
    mqid int not null auto_increment PRIMARY KEY,
    MID VARCHAR(50) REFERENCES MEMBERS(MID),
    MQQUOTE VARCHAR(500) NOT NULL,
    MQLANG VARCHAR(20) NOT NULL,
    MQMEDIA VARCHAR(20) NOT NULL,
    MQWHY VARCHAR(50) NOT NULL,
    MQDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    MQNOTE VARCHAR(500),  
    MQIMPORTANT int(1) DEFAULT 0
);
select last_insert_id(mqid) from MYQBOOK;
INSERT INTO MYQBOOK VALUES(last_insert_id(mqid)+1, 'catgirl@naver.com','security.','English','web page','I hardly understand it',default, null,0);
SELECT MAX(MQID) FROM MYQBOOK;
SELECT*FROM MYQBOOK;

CREATE TABLE SOURCE_INFO(
    MQID int auto_increment PRIMARY KEY REFERENCES MYQBOOK(MQID),
    STITLE VARCHAR(100) NOT NULL,
    SMAKER VARCHAR(100) NOT NULL,
    SURL VARCHAR(300),
    SYEAR VARCHAR(20)
);
INSERT INTO SOURCE_INFO VALUES(last_insert_id(mqid), 'US shutdown begins as Senate fails to pass new budget','BBC','http://www.bbc.com/news/world-us-canada-42757091','2018');
SELECT*FROM SOURCE_INFO;
CREATE TABLE VOCANOTE(
    MQID int auto_increment PRIMARY KEY REFERENCES MYQBOOK(MQID),
    WORD1 VARCHAR(20), 
    MEANING1 VARCHAR(200),
    WORD2 VARCHAR(20),
    MEANING2 VARCHAR(200),
    WORD3 VARCHAR(20),
    MEANING3 VARCHAR(200),
    PHRASE VARCHAR(100),
    MEANING4 VARCHAR(200)
);
INSERT INTO VOCANOTE VALUES(last_insert_id(mqid), 'Senate',' The Senaand Australia.',null,null,null,null,null,null);
SELECT*FROM VOCANOTE;

SELECT Q.*, STITLE,SMAKER,SURL, SYEAR, WORD1,MEANING1, WORD2,MEANING2, WORD3, MEANING3,PHRASE, MEANING4 
	FROM MYQBOOK Q, SOURCE_INFO S, VOCANOTE V 
		WHERE Q.MQID=S.MQID AND S.MQID=V.MQID AND MQLANG='English' 
			ORDER BY MQDATE DESC;
SELECT * FROM MYQBOOK Q, SOURCE_INFO S, VOCANOTE V 
	WHERE Q.MQID=S.MQID AND S.MQID=V.MQID AND MQLANG='German' 
		ORDER BY MQDATE DESC;

/*SELECT*FROM (
	SELECT ROWNUM RN, A.* FROM (
		SELECT B.*, MPHOTO FROM MVC_BOARD B, MVC_MEMBER M 
			WHERE B.MID=M.MID ORDER BY BGROUP DESC, BSTEP) A ) 
				WHERE RN BETWEEN 1 AND 10;*/
            
/*SELECT*FROM (
	SELECT ROWNUM RN, A.* FROM(
		SELECT Q.*,STITLE,SMAKER,SURL,SYEAR,WORD1,MEANING1,WORD2,MEANING2,WORD3,MEANING3,PHRASE,MEANING4 
			FROM MYQBOOK Q, SOURCE_INFO S, VOCANOTE V 
				WHERE Q.MQID=S.MQID AND S.MQID=V.MQID AND MQLANG='English' ORDER BY MQDATE DESC) A ) 
					WHERE RN BETWEEN 1 AND 10;*/
#My English Quotes
select Q.*,STITLE,SMAKER,SURL,SYEAR,WORD1,MEANING1,WORD2,MEANING2,WORD3,MEANING3,PHRASE,MEANING4 
	from MYQBOOK Q, SOURCE_INFO S, VOCANOTE V
		where Q.MQID=S.MQID AND S.MQID=V.MQID AND MQLANG='English'
			order by mqdate desc
				limit 10;
    
                    
SELECT COUNT(*) FROM MYQBOOK WHERE MQLANG='English' AND MID='catgirl@naver.com';

SELECT MQLANG, COUNT(*) FROM MYQBOOK WHERE MID='catgirl@naver.com' GROUP BY MQLANG;

SELECT Q.*, STITLE,SMAKER,SURL, SYEAR, WORD1, MEANING1, WORD2,MEANING2, WORD3, MEANING3,PHRASE, MEANING4 
	FROM MYQBOOK Q, SOURCE_INFO S, VOCANOTE V 
		WHERE Q.MQID=S.MQID AND S.MQID=V.MQID AND Q.MQID=15;

#PUBLIC BOOK
DROP TABLE PUBLICBOOK;
CREATE TABLE PUBLICBOOK(
   PBID int auto_increment PRIMARY KEY,
   MQID int(20) REFERENCES MYQBOOK(MQID),
   MID varchar(50) REFERENCES MEMBERS(MID),
   PBTITLE VARCHAR(150) NOT NULL,
   PBCONTENT VARCHAR(1000) NOT NULL,
   PBDATE timestamp DEFAULT CURRENT_TIMESTAMP,
   PBHIT int DEFAULT 0,
   PBDEL int(1) DEFAULT 0
);
SELECT*FROM PUBLICBOOK;
INSERT INTO PUBLICBOOK VALUES(last_insert_id(PBID)+1, 8, 'catgirl@naver.com', 'Someone help me!', 'I dont understand it at all', default, default, default);
UPDATE PUBLICBOOK SET PBHIT = PBHIT+1 WHERE PBID=1;
SELECT PB.*, MNAME, MPHOTO FROM PUBLICBOOK PB, MEMBERS M WHERE PB.MID=M.MID AND PBID=1;

SELECT PBID, PB.MQID ,MQQUOTE, MQLANG, MQWHY, STITLE, SMAKER, SURL 
	FROM PUBLICBOOK PB, MYQBOOK MQ, SOURCE_INFO S 
		WHERE PB.MQID=MQ.MQID AND MQ.MQID=S.MQID AND PBID=3;

#CONTENTVIEW2 QUOTE INFO
SELECT MAX(PBID) FROM PUBLICBOOK;
/*LIST를 위한 VIEW*/
SELECT PBID, PBTITLE, MQQUOTE, PBDATE, PBHIT, PBDEL,MNAME, MPHOTO 
	FROM PUBLICBOOK as PB, MEMBERS as M, MYQBOOK as MQ 
    WHERE PB.MID=M.MID AND PB.MQID=MQ.MQID ORDER BY PBDATE DESC;
##LIST TOP구문
/*SELECT*FROM 
	(SELECT ROWNUM RN, A.* FROM 
		(SELECT B.*, MPHOTO FROM MVC_BOARD B, MVC_MEMBER M 
			WHERE B.MID=M.MID ORDER BY BGROUP DESC, BSTEP) A ) 
				WHERE RN BETWEEN 1 AND 10;*/
/*SELECT*FROM 
	(SELECT ROWNUM RN, A.* FROM (
		SELECT PBID, PBTITLE, MQQUOTE, PBDATE, PBHIT, PBDEL,MNAME, MPHOTO 
			FROM PUBLICBOOK PB, MEMBERS M, MYQBOOK MQ 
				WHERE PB.MID=M.MID AND PB.MQID=MQ.MQID AND MQLANG='English' 
					ORDER BY PBDATE DESC) A ) 
						WHERE RN BETWEEN 1 AND 5;*/
select PBID, PBTITLE, MQQUOTE, PBDATE, PBHIT, PBDEL,MNAME, MPHOTO
	from PUBLICBOOK PB, MEMBERS M, MYQBOOK MQ 
		where PB.MID=M.MID AND PB.MQID=MQ.MQID AND MQLANG='English'
			order by PBDATE desc
				limit 0,5;
                
SELECT COUNT(*) FROM PUBLICBOOK PB, MYQBOOK MQ WHERE MQLANG='English' AND PB.MQID=MQ.MQID;
commit;

#list for main. recent post 3
SELECT*FROM 
	(SELECT ROWNUM RN, A.* FROM 
		(SELECT PBID, PBTITLE, MQQUOTE, PBDATE, PBHIT, PBDEL, MNAME, MPHOTO 
			FROM PUBLICBOOK PB, MEMBERS M, MYQBOOK MQ 
				WHERE PB.MID=M.MID AND PB.MQID=MQ.MQID AND MQLANG='English' 
					ORDER BY PBDATE DESC) A ) 
						WHERE RN BETWEEN 1 AND 3;
#list for main popular post 3
SELECT*FROM 
	(SELECT ROWNUM RN, A.* FROM 
		(SELECT PBID, PBTITLE, MQQUOTE, PBDATE, PBHIT, PBDEL,MNAME, MPHOTO FROM PUBLICBOOK PB, MEMBERS M, MYQBOOK MQ 
			WHERE PB.MID=M.MID AND PB.MQID=MQ.MQID AND MQLANG='English' 
				ORDER BY PBHIT DESC) A ) WHERE RN BETWEEN 1 AND 3;

#get my quote count
SELECT COUNT(*) FROM MYQBOOK WHERE MID='catgirl@naver.com';
SELECT COUNT(*) FROM PUBLICBOOK WHERE MID='catgirl@naver.com';
#MY RECENT QUOTE 10
SELECT MQQUOTE, MQDATE FROM MYQBOOK WHERE MID='catgirl@naver.com' ORDER BY MQDATE DESC;
SELECT*FROM 
	(SELECT ROWNUM RN, A.* FROM
		(SELECT MQQUOTE, MQDATE FROM MYQBOOK WHERE MID='catgirl@naver.com' 
			ORDER BY MQDATE DESC) A ) WHERE RN BETWEEN 1 AND 10;

#point up
UPDATE MEMBERS SET MPOINT=6000 WHERE MID='choryon2@naver.com';
#check member level
SELECT MID, L.MLEVEL, MPOINT, MLHIGHP, MLNAME FROM MEMBERS M, MLEVEL L WHERE MPOINT BETWEEN MLLOWP AND MLHIGHP AND MID='catgirl@naver.com';
SELECT*FROM MEMBERS;
COMMIT;

SELECT * FROM MYQBOOK MQ, VOCANOTE V WHERE MQ.MQID=V.MQID AND MID='haenemm@naver.com';
SELECT WORD1, WORD2, WORD3 FROM MYQBOOK MQ, VOCANOTE V WHERE MQ.MQID=V.MQID AND MID='haenemm@naver.com';

SELECT COUNT(*) FROM MYQBOOK MQ, VOCANOTE V WHERE MQ.MQID=V.MQID AND MID='haenemm@naver.com' AND WORD1 IS NOT NULL;
SELECT COUNT(*) FROM MYQBOOK MQ, VOCANOTE V WHERE MQ.MQID=V.MQID AND MID='haenemm@naver.com' AND WORD2 IS NOT NULL;
SELECT COUNT(*) FROM MYQBOOK MQ, VOCANOTE V WHERE MQ.MQID=V.MQID AND MID='haenemm@naver.com' AND WORD3 IS NOT NULL;
SELECT COUNT(*) FROM MYQBOOK MQ, VOCANOTE V WHERE MQ.MQID=V.MQID AND MID='haenemm@naver.com' AND PHRASE IS NOT NULL;
